services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8888:8888"
    environment:
      - SERVER_URL=http://server:8888
      - PORT=8888
      - NODE_ENV=production
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - SERVER_URL=http://server:8888
    depends_on:
      - server
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://server:8888"]
      interval: 30s
      timeout: 10s
      retries: 3